pipelines:
  default:
    - step:
        name: Mirror to GitHub
        image: alpine/git
        script:
          - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/andyl-netapp/ontap-mcp-server.git
          - git push github HEAD:main --force
          - git push github --tags --force